apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ KUBE_DEPLOY_GATEWAY }}
  labels:
    app: orca-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orca-gateway
  template:
    metadata:
      labels:
        app: orca-gateway
    spec:
      containers:
        - name: container-orca-gateway
          image: ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_GATEWAY }}:latest
          ports:
            - containerPort: 8000
