server:
  port: 8000

spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

routes:
  services:
    - id: "auth"
      uri: "http://orca-auth:8010"
      path: "/auth/**"
      authRequired: false
    - id: "member"
      uri: "http://orca-member:8020"
      path: "/member/**"
      authRequired: true
    - id: "match"
      uri: "http://orca-match:8030"
      path: "/match/**"
      authRequired: true