server:
  port: 8000

spring:
  application:
    name: 'gateway'
  cloud:
    gateway:
      default-filters:
        - name: DedupeResponseHeader
          args:
            name: Access-Control-Allow-Origin
            strategy: RETAIN_FIRST
      routes:
        - id: auth
          uri: http://orca-auth:8010
          predicates:
            - Path=/auth/**

        - id: member
          uri: http://orca-member:8020
          predicates:
            - Path=/member/**

        - id: match
          uri: http://orca-match:8030
          predicates:
            - Path=/match/**