name: Deploy Gateway

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: deploy
        run: |
          PID=$(lsof -t -i:8000)
          if [ -n "$PID" ]; then
            echo "Stop current application (PID: $PID)."
            kill -9 "$PID"
          else
            echo "Nothing currently running."
          fi
          nohup java -jar $(ls ./build/libs/*.jar | grep -v "plain") --spring.config.location=file:./src/main/resources/ > "../logs/$(date +"%Y%m%d%H%M").log" 2>&1 &
