name: Deploy Gateway

on:
  push:
    branches:
      - main
      - chore/add-k8s # 지워야함

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build --build-arg EUREKA=${{ secrets.KUBE_SERVICE_EUREKA }} -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_GATEWAY }}:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO_GATEWAY }}:latest

      - name: Deploy
        run: |
          kubectl rollout restart deployment/${{secrets.KUBE_DEPLOY_GATEWAY}}
          kubectl rollout status deployment/${{secrets.KUBE_DEPLOY_GATEWAY}}